// Solid/src/index.jsx
/* @refresh reload */
import { render } from 'solid-js/web'
import { Route, Router, Routes } from "@solidjs/router";


import './index.css'
import App from './App'
import Detaillayout from './view/DetailLayout';
import Detail_movie from './view/Detail_movie';
import Detail_person from './view/Detail_person';
import Detail_series from './view/Detail_series';
import SearchPage from './view/SearchPage';

const root = document.getElementById('root')

render(() => (
    <Router>
        <Routes>
            <Route path={'/'} component={App} />
            <Route path={'/detail'} component={Detaillayout} >
                    <Route path={'/movie/:id'} component={Detail_movie}/>
                    <Route path={'/person/:id'} component={Detail_person}/>
                    <Route path={'/tv/:id'} component={Detail_series}/>

            </Route>
            <Route path={'/search'} component={SearchPage} />

        </Routes>
        </Router>


), root)

// React/src/main.jsx
import React, { Children } from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'
import { RouterProvider, createBrowserRouter } from 'react-router-dom'
import MoviesPage from './view/MoviesPage.jsx'
import DetailLayout from './view/DetailLayout.jsx'
import Detail_movie from "./view/Detail_movie.jsx";
import Detail_person from "./view/Detail_person.jsx";
import Detail_series from "./view/Detail_series.jsx";
import { SearchPage } from './view/SearchPage.jsx'

const router = createBrowserRouter([
  {
    path: '/',
    element: <App />,
   
  },
  {
    path:'detail',
    element: <DetailLayout/>,
    children:[
      {
        path:'movies',
        element: <MoviesPage/>,
      },
      {
      path:'movie/:id',
        element:<Detail_movie/>
      },
      {
        path:'person/:id',
        element:<Detail_person/>
      },
      {
        path:'tv/:id',
        element:<Detail_series/>
      }
    ]
  },
  {
    path:'/search',
    element:<SearchPage/>
  }

])



ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
      <RouterProvider router={router} />
  </React.StrictMode>
)
