// Svelte/src/views/Home.svelte
<script>
    import { getPopularMovies,getPopularPeople,getPopularSeries } from "../utils/tmdb";
    import SwiperPart from "../components/SwiperPart.svelte";
    import Navbar from "../components/common/Navbar.svelte";
    import Footer from "../components/common/Footer.svelte";
    let popularMovies 
    let popularPeoples 
    let popularSeries 
    getPopularMovies().then((data) => {
      popularMovies = data;
    });
    getPopularPeople().then((data) => {
      popularPeoples = data;
    });
    getPopularSeries().then(data=>{
      popularSeries = data
    })


</script>

<div class=" min-h-screen flex flex-col">
    <Navbar/>
    <!-- <Navbar /> -->
    <div class="flex flex-col mt-8">
        <SwiperPart head="Popular Movies" movies={popularMovies} />
        <SwiperPart head="Popular Actors" movies={popularPeoples} />
        <SwiperPart head="Popular Series" movies={popularSeries} />
    </div>
    </div>
    <Footer />

// Vue/src/views/Home.vue
<script setup>
import { onMounted, ref } from 'vue';
import {getPopularMovies,getPopularPeople,getPopularSeries} from '../utils/tmdb'
import Swiperpart from '../components/swiperPart.vue';
const popularmovies = ref([])
const popularpeople = ref([])
const popularseries = ref([])
onMounted(async()=>{
    const popularmoviesdata = await  getPopularMovies()
    popularmovies.value = popularmoviesdata
    const popularpeopledata = await getPopularPeople()
    popularpeople.value = popularpeopledata
    const popularseriesdata  = await getPopularSeries()
    popularseries.value = popularseriesdata
})
</script>
<template>
    <Swiperpart head="Popular Movies" :movies="popularmovies"/>
    <Swiperpart head="Popular Actors" :movies="popularpeople"/>
    <Swiperpart head="Popular Series" :movies="popularseries"/>
</template>
